### ISSUE TITLE
[SSL] Plugin doesn't allow private key with password

### ISSUE THREAD

**Issue by ghost** [jurek7/logstash-input-mqtt#10]
Hi,

We're using your plugin with SSL Enabled but our client.key its protected with a password and it needed to be informed so it can be opened successfully. To this date, there's no parameter in your plugin that allows inputing the password for SSL. Is it easy to implement it? I don't know whether paho.mqtt has it too.

Bottom of line, we're using your plugin like this:

```
input {
    mqtt {
                topic               => "ZZZZZZ"
                host                => "${MQTT_HOST}"
                username            => "${MQTT_USERNAME}"
                password            => "${MQTT_PASSWORD}"
                client_id           => "ZZZZZZZ"
                clean_session       => false
                qos                 => 1
                ssl                 => true
                certificate_path    => "${CERT_PATH}/client.crt"
                key_path            => "${CERT_PATH}/client.key"
                root_ca_path        => "${CERT_PATH}/ca.cert"
                # I need to inform the password for client.key
        }
}

```
Thanks in advance.

**Comment by jurek7** [comment]
Hi @casmeiron, 

Please report to paho.mqtt library and link to this issue.

**Comment by ghost** [comment]
it's ok for now to not have this.
