### ISSUE TITLE
Enable Encryption with Certificates

### ISSUE THREAD

**Issue by casmeiron** [jurek7/logstash-input-mqtt#7]
Hi,

Would it be possible to implement in logstash plugin the option to use SSL with certificates? The paho MQTT implementation for ruby allows that as you can see in the follow link:

https://github.com/RubyDevInc/paho.mqtt.ruby/#encrypted-mode

I need to use CARoot certificate for my project. As reading the documentation (and btw I know nothing of ruby), you should only allow to receive the input parameters and apply that in the connection options.

Thanks in advance!

Best Regards.

**Comment by jurek7** [comment]
Good idea, could you please help to prepare scripts for verification using for example mosquitto_pub and mosquitto_sub command ?

**Comment by casmeiron** [comment]
Hi @jurek7 ,

Sure, to subscribe to test.mosquitto.org using only the CA file you can try this:

`mosquitto_sub -h test.mosquitto.org -p 8883 --cafile mosquitto.org.crt -t "#" -v
`

The CA file can be downloaded here: http://test.mosquitto.org/ssl/mosquitto.org.crt

To enable TLS, you have to boot a mosquitto server (test.mosquitto.org isn't' work with your own signed client certificate, tried several times).

Following these simple steps it's possible to try pub/sub with your own instance of mosquitto server:

[](https://primalcortex.wordpress.com/2016/03/31/mqtt-mosquitto-broker-with-ssltls-transport-security/
)
Let me know if you need anything else.

Thanks.

**Comment by casmeiron** [comment]
This is how you subscribe to a server that have the TLS enabled:

> mosquitto_sub -h <server> -p <port> -t '$SYS/#' -v --cafile mosquitto.org.crt --key client.key --cert client.crt

**Comment by consulthys** [comment]
Is someone working on this?
I can lend a hand as I also need this feature.
Let me know

**Comment by jurek7** [comment]
Hi @casmeiron, @consulthys,

I added support for SSL configuration in last commit. Here is my logstash.conf. For me it works well with client certificate and test.mosquitto.org server:

```
input {
  mqtt {
    host => "test.mosquitto.org"
    port => 8884
    topic => "#"
    qos => 2
    codec => plain
    ssl => true
    certificate_path => "/usr/share/logstash/ssl-client/client.crt"
    key_path => "/usr/share/logstash/ssl-client/client.key"
    # root_ca_path => "path to rootCA if needed"
  }
}

#filter {
#	json {
#		source => "message"
#	}
#}

output {
  stdout {}
}
```

**Comment by consulthys** [comment]
Splendid, thanks @jurek7, I'll try this out shortly.

**Comment by jurek7** [comment]
Closing issue. @consulthys please report separate issue for support EC private keys.

**Comment by casmeiron** [comment]
I've tested with modifications and worked like a charm.
Thanks very much!
